[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ignore=openpilot/ --ignore=cereal/ --ignore=opendbc/ --ignore=panda/ --ignore=rednose_repo/ --ignore=tinygrad_repo/ --ignore=teleoprtc_repo/ -Werror --strict-config --strict-markers --durations=10 -n auto --dist=loadgroup"
cpp_files = "test_*"
cpp_harness = "selfdrive/test/cpp_harness.py"
python_files = "test_*.py"
#timeout = "30"  # you get this long by default
markers = [
  "slow: tests that take awhile to run and can be skipped with -m 'not slow'",
  "tici: tests that are only meant to run on the C3/C3X",
]
testpaths = [
  "common",
  "selfdrive/athena",
  "selfdrive/boardd",
  "selfdrive/car",
  "selfdrive/controls",
  "selfdrive/locationd",
  "selfdrive/monitoring",
  "selfdrive/navd/tests",
  "selfdrive/thermald",
  "selfdrive/test/longitudinal_maneuvers",
  "selfdrive/test/process_replay/test_fuzzy.py",
  "selfdrive/updated",
  "system/camerad",
  "system/hardware/tici",
  "system/loggerd",
  "system/proclogd",
  "system/tests",
  "system/ubloxd",
  "system/webrtc",
  "tools/lib/tests",
  "tools/replay",
  "tools/cabana"
]

[tool.mypy]
python_version = "3.11"
plugins = [
  "numpy.typing.mypy_plugin",
]
exclude = [
  "body/",
  "cereal/",
  "opendbc/",
  "panda/",
  "rednose/",
  "rednose_repo/",
  "tinygrad/",
  "tinygrad_repo/",
  "teleoprtc/",
  "teleoprtc_repo/",
  "third_party/",
]

# third-party packages
ignore_missing_imports=true

# helpful warnings
warn_redundant_casts=true
warn_unreachable=true
warn_unused_ignores=true

# restrict dynamic typing
warn_return_any=true

# allow implicit optionals for default args
implicit_optional = true



[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "av",
    "azure-identity",
    "azure-storage-blob",
    "breathe",
    "control",
    "coverage",
    "dictdiffer",
    "ft4222",
    "flaky",
    "hypothesis~=6.47",
    "inputs",
    "Jinja2",
    "lru-dict",
    "matplotlib",
    "metadrive-simulator==0.4.2.3; platform_machine != \"aarch64\"",
    "mpld3",
    "mypy",
    "myst-parser",
    "natsort",
    "opencv-python-headless",
    "parameterized<1.0,>=0.8",
    "pprofile",
    "polyline",
    "pre-commit",
    "pyautogui",
    "pyopencl==2023.1.4",
    "pygame",
    "pywinctl",
    "pyprof2calltree",
    "pytest",
    "pytest-cov",
    "pytest-cpp",
    "pytest-subtests",
    "pytest-xdist",
    "pytest-timeout",
    "pytest-randomly",
    "ruff",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-sitemap",
    "tabulate",
    "tenacity",
    "types-requests",
    "types-tabulate",
    "tqdm",
    "pyqt5==5.15.2; platform_machine == \"x86_64\"",
]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
indent-width = 2
lint.select = ["E", "F", "W", "PIE", "C4", "ISC", "RUF008", "RUF100", "A", "B", "TID251"]
lint.ignore = ["E741", "E402", "C408", "ISC003", "B027", "B024"]
line-length = 160
target-version="py311"
exclude = [
  "body",
  "cereal",
  "panda",
  "opendbc",
  "rednose_repo",
  "tinygrad_repo",
  "teleoprtc",
  "teleoprtc_repo",
  "third_party",
]
lint.flake8-implicit-str-concat.allow-multiline=false
[tool.ruff.lint.flake8-tidy-imports.banned-api]
"selfdrive".msg = "Use openpilot.selfdrive"
"common".msg = "Use openpilot.common"
"system".msg = "Use openpilot.system"
"third_party".msg = "Use openpilot.third_party"
"tools".msg = "Use openpilot.tools"
"pytest.main".msg = "pytest.main requires special handling that is easy to mess up!"

[tool.coverage.run]
concurrency = ["multiprocessing", "thread"]
[tool.ruff.format]
quote-style = "preserve"

[project]
authors = [
    {name = "Vehicle Researcher", email = "user@comma.ai"},
]
license = {text = "MIT"}
requires-python = ">=3.11, <3.12"
dependencies = [
    "aiohttp",
    "aiortc",
    "cffi",
    "crcmod",
    "Cython",
    "json-rpc",
    "libusb1",
    "numpy",
    "onnx>=1.14.0",
    "onnxruntime>=1.16.3; platform_machine == \"aarch64\"",
    #"onnxruntime-gpu>=1.16.3; platform_machine == \"x86_64\"",
    "psutil",
    "pyaudio",
    "pycapnp",
    "pycryptodome",
    "PyJWT",
    "pyserial",
    "pyzmq",
    "requests",
    "scons",
    "sentry-sdk",
    "smbus2",
    "sounddevice",
    "spidev",
    "sympy",
    "websocket-client",
    "casadi",
    "future-fstrings",
    "markdown-it-py",
    "timezonefinder",
    "setproctitle",
]
name = "openpilot"
version = "0.1.0"
description = "an open source driver assistance system"
readme = "README.md"

[project.urls]
repository = "https://github.com/commaai/openpilot"
documentation = "https://docs.comma.ai"
